# Docker image
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Start development environment
    before: echo "nvm use default" >> ~/.bashrc && nvm use default
    init: source ~/.bashrc; yarn && alias near=./node_modules/near-cli/bin/near
    command: yarn dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview